### ISSUE TITLE
Issues with generate_prior_struct

### ISSUE THREAD

**Issue by breanna-binder** [rafaeleufrasio/lightning#7]
Hello- I am trying to run LIGHTNING and am encountering problems with the generate_prior_struct routine. The issue seems to be occurring on lines 92-96; it is not generating the new PSI_1, PSI_2, etc keys. Any assistance would be appreciated. Thank you!

**Comment by kjdoore** [comment]
Hi Breanna!
If you are having an issue in `generate_prior_struct`, then let's start with the most likely option. What version of IDL are you running? I see that we claim IDL 8.0 will work. However, it actually requires IDL 8.3 or later (I will be updating the documentation to reflect this), since we utilize the built-in `orderedhash` routine.

If you are using a version of IDL 8.3 or newer, then it could be a few other issues. It may be easiest if you share your data here (if possible), and I can try some troubleshooting.
Keith

**Comment by breanna-binder** [comment]
Thanks for the quick response! I am running IDL 8.7 (darwin x86_64 m64) on OSX 12.6 (Monterey).  Here is the data file I've been using to test the code on.

[NGC4826_input.txt](https://github.com/rafaeleufrasio/lightning/files/10316378/NGC4826_input.txt)

**Comment by kjdoore** [comment]
Okay, I found the issue. It was in the `ascii_input_to_fits` procedure. The coding for detecting each line start was incorrectly set up for a single SED. I have fixed the issue and pushed the correction. After testing, your input data runs for me using the default configuration.

You will need to pull the changes and rebuild the package using:
```
cd <install_dir>
git pull
idl lightning_build
```
Then you should be able to run with your test SED. If you can let me know if this update worked, I will mark the issue as resolved. Thanks!

**Comment by breanna-binder** [comment]
Thanks - it is now running with the single SED (I actually found that issue yesterday and was able to correct it) - but I'm still getting this error:

% Key does not exist: "PSI_1"

**Comment by kjdoore** [comment]
Okay, are you using the default configuration? If not, are you using the interactive or file configuration method. In this case it seems that you may not be using a stellar model when Lightning expects it. (It should automatically flag situations like this. If it is not, that will need to be fixed.) Could you give me a general idea what configuration you are trying to use (i.e., what models)?

**Comment by breanna-binder** [comment]
I am using the default configuration with the file configuration method. (Side note: when I try to run the interactive mode it complains that there is no 'COSMOLOGY' key and then quits).

**Comment by kjdoore** [comment]
Hi Breanna,
After doing some extensive troubleshooting last night and this morning, I nor my collaborator @ebmonson can seem to replicate your issue. Our best guess is that it is some issue with the dependency on the IDLAstro library or Coyote library. Do you know what version of these libraries you are using (i.e., when did you download them)? It may be that when you run Lightning an older version of some utilized function from IDLAstro in your path and is being compiled rather than the more recent version Lightning expects. (Lightning expects the most recent versions posted on [GitHub](https://github.com/wlandsman/IDLAstro).)

We recommend doing a fresh install of both Lightning and it dependencies ([IDLAstro](https://github.com/wlandsman/IDLAstro), [Coyote](http://www.idlcoyote.com/documents/programs.php), and [MPFIT](https://pages.physics.wisc.edu/~craigm/idl/fitting.html)) in a new directory. Then, you can temporarily override and update your IDL path to only include the dependencies with:
```
IDL> !PATH = EXPAND_PATH('<IDL_DEFAULT>:+<path_to_install_dir>/IDLAstro:+<path_to_install_dir>/coyote:+<path_to_install_dir>/mpfit')
```
where `<path_to_install_dir>` is wherever you installed the libraries. Doing this should allow for you to fit the SED (at least it did for each of us). Let me know how this goes or if you need any more assistance!

**Comment by breanna-binder** [comment]
Thank you for looking into this. I followed your suggestion and did a full fresh install of Lightning and the IDL libraries (including updating my IDL path to point to the new installs), but I am still getting the same error: Key does not exist: "PSI_1". Not sure what is missing on my machine, but I hate to take up any more of your time. Thank you again!
